### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by fancyboynet** [qdsang/fis-parser-compass#3]
Downloading http://fisstatic.duapp.com/addons/fis-sass/0.2.0/darwin-x64/0.9.11/binding.node ...
Received 512K...
Received 1029K...
Received 1485K total.
Test failed!
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/binding/binding.o
  CXX(target) Release/obj.target/binding/lib/sync.o
../lib/sync.cc:58:51: error: no member named 'New' in 'v8::String'
  Local<Value> output = Local<Value>::New(String::New(converted));
                                          ~~~~~~~~^
1 error generated.
make: **\* [Release/obj.target/binding/lib/sync.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/fis-parser-compass/node_modules/fis-parser-sass/node_modules/fis-sass
gyp ERR! node -v v0.12.2
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok 
Build failed
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/ngds/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/ngds/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "install" "-g" "fis-parser-compass"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE

npm ERR! fis-sass@0.2.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fis-sass@0.2.0 install script 'node build.js'.
npm ERR! This is most likely a problem with the fis-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fis-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ngds/npm-debug.log

**Comment by qdsang** [comment]
目前依赖的sass 不支持node 0.12.x
可以提交一个Pull requests， 或者按照 https://github.com/fex-team/fis-parser-sass/blob/master/README.md 提供的方法一步步做
还是很期待你能PR~

**Comment by fancyboynet** [comment]
意思是要自己先装fis-parser-sass吗？

**Comment by qdsang** [comment]
可以直接按照 https://github.com/fex-team/fis-parser-sass/blob/master/README.md#%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8sass%E5%92%8Ccompass 这个解决办法解决

**Comment by fancyboynet** [comment]
这个我试过。。。也提过issue了，用了之后css sprite失效了，所以才找到这里来的...

**Comment by qdsang** [comment]
这确实蛋疼
降node版本到0.10.x， 可以使用compass现在这个版本

**Comment by fancyboynet** [comment]
嗯，没事，我只是在尝试fis跟compass怎么用，降node就不要了，暂时还是先混着用吧，有能力再看能不能一起优化下这个插件

**Comment by qdsang** [comment]
赞！
